-- ═══════════════════════════════════════════════════════════════
-- 🗄️  OTTOMAN GAME BOT – COMPLETE DATABASE SETUP
--     شغّل هذا الملف مرة واحدة في Supabase SQL Editor
--     يُنشئ كل الجداول + الدوال + الـ Triggers + سياسات RLS
-- ═══════════════════════════════════════════════════════════════


-- ╔═══════════════════════════════════════════════════════════════╗
-- ║  SECTION 1 – HELPER FUNCTIONS (needed before triggers)       ║
-- ╚═══════════════════════════════════════════════════════════════╝

-- دالة تحديث updated_at تلقائياً
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- دالة تحويل اسم المستخدم إلى أحرف صغيرة
CREATE OR REPLACE FUNCTION public.normalize_username()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.username IS NOT NULL THEN
    NEW.username = lower(NEW.username);
  END IF;
  RETURN NEW;
END;
$$;


-- ╔═══════════════════════════════════════════════════════════════╗
-- ║  SECTION 2 – TABLES                                          ║
-- ╚═══════════════════════════════════════════════════════════════╝

-- ────────────────────────────────────────────────────────────────
-- ① جدول user_roles  (نظام الأدوار: admin / user)
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_roles (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE NOT NULL,
  role    TEXT NOT NULL DEFAULT 'user',
  CONSTRAINT valid_role CHECK (role IN ('user', 'admin'))
);

-- ────────────────────────────────────────────────────────────────
-- ② جدول profiles  (بيانات المستخدم الممتدة)
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.profiles (
  id              UUID NOT NULL,
  username        TEXT NULL,
  full_name       TEXT NULL,
  updated_at      TIMESTAMP WITH TIME ZONE NULL DEFAULT now(),
  created_at      TIMESTAMP WITH TIME ZONE NULL DEFAULT now(),
  allowed_accounts NUMERIC NULL,
  "Is_COMP"       BOOLEAN NULL,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id)
    REFERENCES auth.users (id) ON DELETE CASCADE,
  CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

-- فهارس profiles
CREATE UNIQUE INDEX IF NOT EXISTS profiles_username_lower_idx
  ON public.profiles USING btree (lower(username))
  WHERE (username IS NOT NULL);

CREATE INDEX IF NOT EXISTS profiles_created_at_idx
  ON public.profiles USING btree (created_at);

-- Triggers لـ profiles
DROP TRIGGER IF EXISTS profiles_set_updated_at ON public.profiles;
CREATE TRIGGER profiles_set_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS profiles_normalize_username ON public.profiles;
CREATE TRIGGER profiles_normalize_username
  BEFORE INSERT OR UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.normalize_username();

-- ────────────────────────────────────────────────────────────────
-- ③ جدول Accounts  (حسابات اللعبة)
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public."Accounts" (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  "Email"           TEXT NULL,
  password          TEXT NULL,
  "Collect_resources" JSONB NULL,
  "Attack resources"  JSONB NULL,
  "Protection"      BOOLEAN NULL,
  "Troops"          BOOLEAN NULL,
  "Not_store"       BOOLEAN NULL,
  "Is_OK"           BOOLEAN NULL,
  user_id           TEXT NULL,
  "Id_Emulators"    TEXT NULL,
  index_server      TEXT NULL,
  "Date_OK"         DATE NULL,
  animal            TEXT NULL,
  CONSTRAINT "Accounts_pkey" PRIMARY KEY (id)
) TABLESPACE pg_default;

-- ────────────────────────────────────────────────────────────────
-- ④ جدول admin_settings  (إعدادات النظام)
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.admin_settings (
  id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  key   TEXT NOT NULL,
  value TEXT NOT NULL,
  CONSTRAINT admin_settings_pkey PRIMARY KEY (id),
  CONSTRAINT admin_settings_key_key UNIQUE (key)
) TABLESPACE pg_default;

-- القيم الافتراضية للإعدادات (يمكنك تعديلها لاحقاً)
INSERT INTO public.admin_settings (key, value)
VALUES
  ('max_accounts_per_server', '50'),
  ('server_count', '5')
ON CONFLICT (key) DO NOTHING;


-- ╔═══════════════════════════════════════════════════════════════╗
-- ║  SECTION 3 – BUSINESS LOGIC FUNCTIONS                        ║
-- ╚═══════════════════════════════════════════════════════════════╝

-- دالة is_admin: هل المستخدم الحالي أدمن؟
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = auth.uid()
      AND role = 'admin'
  );
$$;


-- دالة reindex_accounts_v2
-- توزع الحسابات المعتمدة على السيرفرات بالتسلسل
CREATE OR REPLACE FUNCTION public.reindex_accounts_v2()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_max_per_server   INT;
  v_server_count     INT;
  v_total_slots      INT;
  v_rec              RECORD;
  v_slot             INT := 0;
BEGIN
  -- اقرأ الإعدادات
  SELECT value::INT INTO v_max_per_server
  FROM public.admin_settings WHERE key = 'max_accounts_per_server';
  v_max_per_server := COALESCE(v_max_per_server, 50);

  SELECT value::INT INTO v_server_count
  FROM public.admin_settings WHERE key = 'server_count';
  v_server_count := COALESCE(v_server_count, 5);

  v_total_slots := v_max_per_server * v_server_count;

  -- أصفر index_server لكل الحسابات غير المعتمدة أولاً
  UPDATE public."Accounts"
  SET index_server = NULL
  WHERE "Is_OK" = false OR "Is_OK" IS NULL;

  -- وزّع الحسابات المعتمدة على السيرفرات بالترتيب
  FOR v_rec IN
    SELECT id
    FROM public."Accounts"
    WHERE "Is_OK" = true
    ORDER BY "Date_OK" ASC, id ASC
  LOOP
    IF v_slot < v_total_slots THEN
      UPDATE public."Accounts"
      SET index_server = ((v_slot / v_max_per_server) + 1)::TEXT
      WHERE id = v_rec.id;
      v_slot := v_slot + 1;
    ELSE
      -- تجاوز الطاقة: ألغِ الاعتماد
      UPDATE public."Accounts"
      SET "Is_OK" = false, index_server = NULL
      WHERE id = v_rec.id;
    END IF;
  END LOOP;
END;
$$;


-- دالة auto_approve_user_accounts
-- تعتمد تلقائياً أقدم N حساب للمستخدم بناءً على الكوتا
CREATE OR REPLACE FUNCTION public.auto_approve_user_accounts(p_user_id TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_quota      INT;
  v_is_comp    BOOLEAN;
  v_approved   INT[];
  v_rejected   INT[];
BEGIN
  -- اجلب الكوتا وحالة المستخدم
  SELECT COALESCE(allowed_accounts, 0)::INT, COALESCE("Is_COMP", false)
  INTO v_quota, v_is_comp
  FROM public.profiles
  WHERE id = p_user_id::UUID;

  IF NOT FOUND THEN RETURN; END IF;

  -- إذا المستخدم غير مفعّل، ألغِ كل حساباته
  IF v_is_comp = false THEN
    UPDATE public."Accounts"
    SET "Is_OK" = false, index_server = NULL
    WHERE user_id = p_user_id;
    PERFORM public.reindex_accounts_v2();
    RETURN;
  END IF;

  -- اجمع IDs الحسابات مرتبة بالأقدم
  SELECT
    array_agg(id ORDER BY created_at ASC) FILTER (WHERE ordinality <= v_quota),
    array_agg(id ORDER BY created_at ASC) FILTER (WHERE ordinality >  v_quota)
  INTO v_approved, v_rejected
  FROM (
    SELECT id, created_at,
           row_number() OVER (ORDER BY created_at ASC) AS ordinality
    FROM public."Accounts"
    WHERE user_id = p_user_id
  ) sub;

  -- اعتمد الأقدم N
  IF v_approved IS NOT NULL AND array_length(v_approved, 1) > 0 THEN
    UPDATE public."Accounts"
    SET "Is_OK" = true
    WHERE id = ANY(v_approved);
  END IF;

  -- ألغِ الباقين
  IF v_rejected IS NOT NULL AND array_length(v_rejected, 1) > 0 THEN
    UPDATE public."Accounts"
    SET "Is_OK" = false, index_server = NULL
    WHERE id = ANY(v_rejected);
  END IF;

  -- أعد توزيع السيرفرات
  PERFORM public.reindex_accounts_v2();
END;
$$;


-- دالة auto_approve_all_users
-- تطبق auto_approve على جميع المستخدمين دفعةً واحدة
CREATE OR REPLACE FUNCTION public.auto_approve_all_users()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user RECORD;
BEGIN
  FOR v_user IN
    SELECT id::TEXT FROM public.profiles
  LOOP
    PERFORM public.auto_approve_user_accounts(v_user.id);
  END LOOP;
END;
$$;


-- دالة handle_new_user  (Trigger على auth.users)
-- تُنشئ profile تلقائياً عند تسجيل مستخدم جديد
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, username, full_name)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1)),
    COALESCE(NEW.raw_user_meta_data->>'full_name', '')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

-- ربط الـ Trigger بجدول auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ╔═══════════════════════════════════════════════════════════════╗
-- ║  SECTION 4 – ROW LEVEL SECURITY (RLS)                        ║
-- ╚═══════════════════════════════════════════════════════════════╝

-- ── user_roles ──────────────────────────────────────────────────
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_roles: self read"  ON public.user_roles;
DROP POLICY IF EXISTS "user_roles: admin full" ON public.user_roles;

CREATE POLICY "user_roles: self read"
  ON public.user_roles FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "user_roles: admin full"
  ON public.user_roles FOR ALL
  USING (public.is_admin());

-- ── profiles ────────────────────────────────────────────────────
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles: self read"    ON public.profiles;
DROP POLICY IF EXISTS "profiles: self update"  ON public.profiles;
DROP POLICY IF EXISTS "profiles: admin full"   ON public.profiles;

CREATE POLICY "profiles: self read"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "profiles: self update"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

CREATE POLICY "profiles: admin full"
  ON public.profiles FOR ALL
  USING (public.is_admin());

-- ── Accounts ────────────────────────────────────────────────────
ALTER TABLE public."Accounts" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "accounts: owner select" ON public."Accounts";
DROP POLICY IF EXISTS "accounts: owner insert" ON public."Accounts";
DROP POLICY IF EXISTS "accounts: owner update" ON public."Accounts";
DROP POLICY IF EXISTS "accounts: owner delete" ON public."Accounts";

-- المستخدم يرى حساباته فقط (نستخدم user_id مباشرة بدلاً من Emulators)
CREATE POLICY "accounts: owner select"
  ON public."Accounts" FOR SELECT
  USING (auth.uid()::TEXT = user_id);

CREATE POLICY "accounts: owner insert"
  ON public."Accounts" FOR INSERT
  WITH CHECK (auth.uid()::TEXT = user_id);

CREATE POLICY "accounts: owner update"
  ON public."Accounts" FOR UPDATE
  USING (auth.uid()::TEXT = user_id);

CREATE POLICY "accounts: owner delete"
  ON public."Accounts" FOR DELETE
  USING (auth.uid()::TEXT = user_id);

-- ── admin_settings ──────────────────────────────────────────────
ALTER TABLE public.admin_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "settings: public read"  ON public.admin_settings;
DROP POLICY IF EXISTS "settings: admin write"  ON public.admin_settings;

-- الكل يقرأ الإعدادات
CREATE POLICY "settings: public read"
  ON public.admin_settings FOR SELECT
  USING (true);

-- الأدمن فقط يعدّل
CREATE POLICY "settings: admin write"
  ON public.admin_settings FOR ALL
  USING (public.is_admin());


-- ╔═══════════════════════════════════════════════════════════════╗
-- ║  SECTION 5 – ADMIN USER SETUP                                ║
-- ║  بعد تشغيل هذا الملف:                                       ║
-- ║  1. سجّل دخولك للتطبيق                                      ║
-- ║  2. اجلب UUID الخاص بك من:                                  ║
-- ║     Authentication → Users في Supabase Dashboard             ║
-- ║  3. شغّل الأمر أدناه مع UUID الصحيح                        ║
-- ╚═══════════════════════════════════════════════════════════════╝

-- INSERT INTO public.user_roles (user_id, role)
-- VALUES ('YOUR-ADMIN-UUID-HERE', 'admin')
-- ON CONFLICT (user_id) DO UPDATE SET role = 'admin';


-- ╔═══════════════════════════════════════════════════════════════╗
-- ║  SECTION 6 – VERIFICATION QUERIES (uncomment to check)       ║
-- ╚═══════════════════════════════════════════════════════════════╝

-- تحقق من الجداول
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name;

-- تحقق من الدوال
-- SELECT routine_name FROM information_schema.routines WHERE routine_schema = 'public' ORDER BY routine_name;

-- تحقق من سياسات RLS
-- SELECT schemaname, tablename, policyname, cmd FROM pg_policies WHERE schemaname = 'public' ORDER BY tablename, policyname;

-- تحقق من الـ Triggers
-- SELECT trigger_name, event_object_table, action_timing, event_manipulation FROM information_schema.triggers WHERE trigger_schema = 'public' ORDER BY event_object_table;
