-- ═══════════════════════════════════════════════════════════════
-- 🔐 OTTOMAN GAME BOT – SECURITY SETUP (RLS + POLICIES)
-- شغّل هذا الملف مرة واحدة في Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════════

-- ────────────────────────────────────────────────────────────────
-- ⓪ تعريف دالة مساعدة: هل المستخدم الحالي أدمن؟
-- ────────────────────────────────────────────────────────────────
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = auth.uid()
      and role = 'admin'
  );
$$;

-- ────────────────────────────────────────────────────────────────
-- ① جدول user_roles
-- ────────────────────────────────────────────────────────────────
create table if not exists public.user_roles (
  id      bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade unique not null,
  role    text not null default 'user',
  constraint valid_role check (role in ('user', 'admin'))
);

alter table public.user_roles enable row level security;

-- المستخدم يرى دوره فقط
create policy "user_roles: self read"
  on public.user_roles for select
  using (auth.uid() = user_id);

-- الأدمن يرى كل الأدوار
create policy "user_roles: admin full"
  on public.user_roles for all
  using (public.is_admin());

-- ────────────────────────────────────────────────────────────────
-- ② جدول Emulators
-- ────────────────────────────────────────────────────────────────
alter table public."Emulators" enable row level security;

-- المستخدم يدير محاكياته فقط
create policy "emulators: owner all"
  on public."Emulators" for all
  using (auth.uid()::text = user_id)
  with check (auth.uid()::text = user_id);

-- الأدمن يرى ويعدّل كل شيء (عبر service_role في الكود)
-- لا نحتاج policy للأدمن لأن callReindex يستخدم supabaseAdmin (service_role)

-- ────────────────────────────────────────────────────────────────
-- ③ جدول Accounts
-- ────────────────────────────────────────────────────────────────
alter table public."Accounts" enable row level security;

-- المستخدم يدير حسابات محاكياته فقط
-- نقسّم إلى 4 سياسات منفصلة لتفادي تعارض RLS مع subquery في with check

create policy "accounts: owner select"
  on public."Accounts" for select
  using (
    exists (
      select 1 from public."Emulators" e
      where e.id::text = "Id_Emulators"
        and e.user_id = auth.uid()::text
    )
  );

create policy "accounts: owner insert"
  on public."Accounts" for insert
  with check (
    exists (
      select 1 from public."Emulators" e
      where e.id::text = "Id_Emulators"
        and e.user_id = auth.uid()::text
    )
  );

create policy "accounts: owner update"
  on public."Accounts" for update
  using (
    exists (
      select 1 from public."Emulators" e
      where e.id::text = "Id_Emulators"
        and e.user_id = auth.uid()::text
    )
  );

create policy "accounts: owner delete"
  on public."Accounts" for delete
  using (
    exists (
      select 1 from public."Emulators" e
      where e.id::text = "Id_Emulators"
        and e.user_id = auth.uid()::text
    )
  );

-- ────────────────────────────────────────────────────────────────
-- ④ جدول subscriptions
-- ────────────────────────────────────────────────────────────────
alter table public.subscriptions enable row level security;

-- المستخدم يرى اشتراكاته فقط
create policy "subscriptions: owner read"
  on public.subscriptions for select
  using (user_id = auth.uid()::text);

-- الأدمن يدير كل الاشتراكات
create policy "subscriptions: admin all"
  on public.subscriptions for all
  using (public.is_admin());

-- ────────────────────────────────────────────────────────────────
-- ⑤ جدول admin_settings
-- ────────────────────────────────────────────────────────────────
alter table public.admin_settings enable row level security;

-- الكل يقرأ الإعدادات (للـ reindex وعرض الحدود)
create policy "settings: public read"
  on public.admin_settings for select
  using (true);

-- الأدمن فقط يعدّل (أو service_role)
create policy "settings: admin write"
  on public.admin_settings for all
  using (public.is_admin());

-- ────────────────────────────────────────────────────────────────
-- ⑥ تعيين حساب الأدمن
--    استبدل 'YOUR-USER-UUID' بالـ UUID الحقيقي من:
--    Supabase Dashboard → Authentication → Users
-- ────────────────────────────────────────────────────────────────
-- insert into public.user_roles (user_id, role)
-- values ('YOUR-USER-UUID-HERE', 'admin')
-- on conflict (user_id) do update set role = 'admin';

-- ────────────────────────────────────────────────────────────────
-- ⑦ منع تسجيل حسابات جديدة (اختياري — إذا أردت دعوة فقط)
-- ────────────────────────────────────────────────────────────────
-- في Supabase Dashboard:
-- Authentication → Settings → "Disable email signups" = ON
-- أو أضف trigger للتحقق من قائمة البريد المسموح بها

-- ────────────────────────────────────────────────────────────────
-- ⑧ التحقق من صحة السياسات
-- ────────────────────────────────────────────────────────────────
-- select schemaname, tablename, policyname, cmd, qual
-- from pg_policies
-- where schemaname = 'public'
-- order by tablename, policyname;
