import { useState, useEffect } from "react";
import { Save, Settings2, AlertCircle, Info, Server, Copy, Check, RefreshCw, Plus, Minus } from "lucide-react";
import { useGetSettings, useUpdateSetting } from "../../hooks/useSettings";
import { useGetAllEmulators } from "../../hooks/useAdminEmulators";
import { toast } from "sonner";
import { useLanguage } from "../../Context/LanguageContext";

// ─── SQL كامل ─────────────────────────────────────────
const FULL_SETUP_SQL = `-- ════════════════════════════════════════════════
-- 🚀 OTTOMAN GAME BOT - SUPABASE SETUP (FULL)
-- ════════════════════════════════════════════════

-- ① جدول الإعدادات
create table if not exists public.admin_settings (
  id    bigint generated by default as identity primary key,
  key   text unique not null,
  value text not null
);
insert into admin_settings (key, value) values
  ('max_per_server', '8'),
  ('total_servers',  '3'),
  ('server_limits',  '{"1":8,"2":8,"3":8}')
on conflict (key) do nothing;

-- ② جدول المحاكيات
create table if not exists public."Emulators" (
  id               bigint generated by default as identity primary key,
  created_at       timestamp with time zone default now(),
  user_id          uuid references auth.users(id) on delete cascade,
  "Is_OK"          text default 'false',
  "Date_OK"        timestamp with time zone,
  index_server     int,
  index_emulators  int
);

-- ③ جدول الحسابات
-- تم مطابقة أسماء الأعمدة لتتوافق تماماً مع كود React
create table if not exists public."Accounts" (
  id                   bigint generated by default as identity primary key,
  created_at           timestamp with time zone default now(),
  "Id_Emulators"       bigint references public."Emulators"(id) on delete cascade,
  "user_id"            text not null,
  "Email"              text not null,
  "password"           text not null,
  "Collect_resources"  boolean[] default '{false,false,false,false}',
  "Attack resources"   text[],
  "Protection"         boolean default false,
  "Troops"             boolean default false,
  "Not_store"          boolean default false,
  "Is_OK"              boolean default false
);

-- ④ جدول الاشتراكات
create table if not exists public.subscriptions (
  id           bigint generated by default as identity primary key,
  created_at   timestamp with time zone default now(),
  user_id      text not null,
  emulator_id  bigint references public."Emulators"(id) on delete cascade,
  month        text not null,
  is_paid      boolean default false,
  paid_at      timestamp with time zone
);

-- ⑤ جدول الأدوار
create table if not exists public.user_roles (
  id      bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade unique,
  role    text not null default 'user'
);

-- ⑥ دالة إعادة الفهرسة (v2) - تدعم حدوداً مختلفة لكل سيرفر
create or replace function reindex_emulators_v2(p_server_limits jsonb)
returns void language plpgsql as $$
declare
  rec           record;
  server_num    int := 1;
  slot_num      int := 1;
  current_limit int;
begin
  -- reset non-approved
  update public."Emulators"
  set index_emulators = null, index_server = null
  where "Is_OK" != 'true';

  for rec in
    select id from public."Emulators"
    where "Is_OK" = 'true'
    order by id
  loop
    current_limit := coalesce((p_server_limits->>(server_num::text))::int, 8);

    -- انتقل للسيرفر التالي إذا امتلأ الحالي
    if slot_num > current_limit then
      server_num := server_num + 1;
      slot_num   := 1;
      current_limit := coalesce((p_server_limits->>(server_num::text))::int, 8);
    end if;

    update public."Emulators"
    set index_emulators = slot_num,
        index_server    = server_num
    where id = rec.id;

    slot_num := slot_num + 1;
  end loop;
end;
$$;

-- ⑦ الدالة القديمة (للتوافق مع الإصدارات القديمة)
create or replace function reindex_emulators(p_max_per_server int)
returns void language plpgsql as $$
begin
  perform reindex_emulators_v2(
    (select jsonb_object_agg(gs::text, p_max_per_server)
     from generate_series(1, 10) gs)
  );
end;
$$;

-- ⑧ سياسات RLS
alter table public."Emulators"   enable row level security;
alter table public."Accounts"    enable row level security;
alter table public.subscriptions  enable row level security;
alter table public.user_roles    enable row level security;
alter table public.admin_settings enable row level security;

create policy if not exists "users_own_emulators" on public."Emulators"
  for all using (auth.uid() = user_id);

create policy if not exists "users_own_accounts" on public."Accounts"
  for all using ("user_id" = auth.uid()::text);

create policy if not exists "read_settings" on public.admin_settings
  for select using (true);

-- ⑨ تعيين أدمن (عدّل UUID)
-- insert into public.user_roles (user_id, role)
-- values ('YOUR-USER-UUID-HERE', 'admin')
-- on conflict (user_id) do update set role = 'admin';`;

// ─── SettingCard: مكون بطاقة إعداد قابل لإعادة الاستخدام ──────────
function SettingCard({ icon: Icon, iconColor, title, hint, children }) {
    return (
        <div className="card" style={{ padding: "1.5rem" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "1.25rem" }}>
                <Icon size={20} color={iconColor || "var(--accent)"} />
                <h2 style={{ font: "700 1rem/1 inherit" }}>{title}</h2>
            </div>
            {children}
            {hint && (
                <div style={{ marginTop: "0.875rem", padding: "0.625rem 0.875rem", background: "var(--accent-soft)", border: "1px solid rgba(108,99,255,0.15)", borderRadius: "var(--radius-sm)" }}>
                    <p style={{ fontSize: "0.8rem", color: "var(--text-secondary)" }}>
                        <Info size={12} style={{ display: "inline", marginRight: 4, color: iconColor || "var(--accent)" }} />
                        {hint}
                    </p>
                </div>
            )}
        </div>
    );
}

// ─── الصفحة الرئيسية ──────────────────────────────────────────────
export default function SettingsAdmin() {
    const { t } = useLanguage();
    const { data: settings, isLoading } = useGetSettings();
    const updateSetting = useUpdateSetting();
    const { data: emulators } = useGetAllEmulators();

    // الإعدادات العامة
    const [maxValue, setMaxValue] = useState("");
    const [serversValue, setServersValue] = useState("");
    const [copied, setCopied] = useState(false);

    // حدود كل سيرفر على حدة
    const [serverLimits, setServerLimits] = useState({});
    const [limitsEdited, setLimitsEdited] = useState(false);

    const currentMax = settings?.max_per_server || "8";
    const currentServers = parseInt(settings?.total_servers || "3", 10);

    // تحميل server_limits من الإعدادات
    useEffect(() => {
        if (!settings) return;
        let parsed = {};
        try { parsed = JSON.parse(settings.server_limits || "{}"); } catch (_) { }
        // أنشئ كائناً بعدد السيرفرات مع قيمة افتراضية
        const filled = {};
        for (let i = 1; i <= currentServers; i++) {
            filled[String(i)] = String(parsed[String(i)] || currentMax);
        }
        setServerLimits(filled);
        setLimitsEdited(false);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [settings]);

    // ── Stats ──
    const approvedCount = emulators?.filter(e => e.Is_OK === "true").length || 0;
    const totalSlots = Object.values(serverLimits).reduce((s, v) => s + parseInt(v || 0, 10), 0);
    const usedServers = [...new Set(emulators?.filter(e => e.Is_OK === "true").map(e => e.index_server))].filter(Boolean).length;
    const usedPct = totalSlots > 0 ? Math.round((approvedCount / totalSlots) * 100) : 0;

    // ── Handlers ──
    const handleSaveMax = () => {
        const val = parseInt(maxValue, 10);
        if (isNaN(val) || val < 1) return toast.error(t("enterValidNumber"));
        updateSetting.mutate({ key: "max_per_server", value: val }, { onSuccess: () => setMaxValue("") });
    };

    const handleSaveServers = () => {
        const val = parseInt(serversValue, 10);
        if (isNaN(val) || val < 1) return toast.error(t("enterValidNumber"));
        updateSetting.mutate({ key: "total_servers", value: val }, { onSuccess: () => setServersValue("") });
    };

    const handleLimitChange = (serverNum, value) => {
        setServerLimits(prev => ({ ...prev, [String(serverNum)]: value }));
        setLimitsEdited(true);
    };

    const handleSaveLimits = () => {
        // تحقق من صحة القيم
        for (const [k, v] of Object.entries(serverLimits)) {
            const n = parseInt(v, 10);
            if (isNaN(n) || n < 1) return toast.error(`السيرفر ${k}: ${t("enterValidNumber")}`);
        }
        const json = JSON.stringify(
            Object.fromEntries(Object.entries(serverLimits).map(([k, v]) => [k, parseInt(v, 10)]))
        );
        updateSetting.mutate({ key: "server_limits", value: json }, {
            onSuccess: () => setLimitsEdited(false),
        });
    };

    const handleApplyDefault = () => {
        // ملء جميع السيرفرات بالقيمة الافتراضية
        const filled = {};
        for (let i = 1; i <= currentServers; i++) filled[String(i)] = currentMax;
        setServerLimits(filled);
        setLimitsEdited(true);
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(FULL_SETUP_SQL).then(() => {
            setCopied(true);
            toast.success("✅ تم نسخ SQL بنجاح!");
            setTimeout(() => setCopied(false), 3000);
        });
    };

    return (
        <div className="animate-fade-in" style={{ display: "flex", flexDirection: "column", gap: "1.75rem" }}>

            {/* Header */}
            <div>
                <h1 style={{ fontSize: "1.5rem", fontWeight: 800, marginBottom: "0.25rem" }}>{t("settings")}</h1>
                <p style={{ color: "var(--text-muted)", fontSize: "0.875rem" }}>{t("emulatorSettings")}</p>
            </div>

            {/* ── الإعدادات العامة ── */}
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: "1.25rem" }}>

                {/* حد افتراضي لكل سيرفر */}
                <SettingCard
                    icon={Settings2}
                    title={t("maxEmulatorsPerServer")}
                    hint={t("settingsReindexHint")}
                >
                    <label className="form-label" style={{ marginBottom: "0.5rem" }}>
                        {t("currentValue")}: <strong style={{ color: "var(--accent)" }}>{isLoading ? "..." : currentMax}</strong>
                    </label>
                    <div style={{ display: "flex", gap: "0.75rem" }}>
                        <input className="form-input" type="number" min={1} max={100}
                            placeholder={currentMax} value={maxValue}
                            onChange={(e) => setMaxValue(e.target.value)} style={{ flex: 1 }} />
                        <button className="btn btn-primary" onClick={handleSaveMax}
                            disabled={updateSetting.isPending || !maxValue}>
                            <Save size={15} /> {t("save")}
                        </button>
                    </div>
                </SettingCard>

                {/* عدد السيرفرات */}
                <SettingCard
                    icon={Server}
                    iconColor="var(--green)"
                    title={t("totalServers") || "عدد السيرفرات"}
                    hint={t("totalServersHint") || "عدد السيرفرات الفعلية المتاحة في النظام."}
                >
                    <label className="form-label" style={{ marginBottom: "0.5rem" }}>
                        {t("currentValue")}: <strong style={{ color: "var(--green)" }}>{isLoading ? "..." : currentServers}</strong>
                    </label>
                    <div style={{ display: "flex", gap: "0.75rem" }}>
                        <input className="form-input" type="number" min={1} max={99}
                            placeholder={String(currentServers)} value={serversValue}
                            onChange={(e) => setServersValue(e.target.value)} style={{ flex: 1 }} />
                        <button className="btn btn-primary" onClick={handleSaveServers}
                            disabled={updateSetting.isPending || !serversValue}
                            style={{ background: "var(--green)" }}>
                            <Save size={15} /> {t("save")}
                        </button>
                    </div>
                </SettingCard>
            </div>

            {/* ── حدود كل سيرفر على حدة ── */}
            <div className="card" style={{ padding: "1.5rem" }}>
                <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "1.25rem", flexWrap: "wrap", gap: "0.5rem" }}>
                    <div style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
                        <Server size={20} color="var(--accent)" />
                        <h2 style={{ font: "700 1rem/1 inherit" }}>حدود كل سيرفر على حدة</h2>
                    </div>
                    <div style={{ display: "flex", gap: "0.5rem" }}>
                        <button className="btn btn-ghost"
                            onClick={handleApplyDefault}
                            style={{ fontSize: "0.8rem", gap: "0.35rem" }}
                            title="تطبيق الحد الافتراضي على جميع السيرفرات">
                            <RefreshCw size={14} /> تطبيق الافتراضي
                        </button>
                        <button
                            className="btn btn-primary"
                            onClick={handleSaveLimits}
                            disabled={updateSetting.isPending || !limitsEdited}
                            style={{ gap: "0.4rem", fontSize: "0.85rem" }}
                        >
                            {updateSetting.isPending
                                ? <div className="spinner" style={{ width: 14, height: 14, borderWidth: 2, borderTopColor: "white" }} />
                                : <Save size={14} />}
                            حفظ التغييرات
                        </button>
                    </div>
                </div>

                {/* شبكة السيرفرات */}
                <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))", gap: "0.75rem" }}>
                    {Array.from({ length: currentServers }, (_, i) => {
                        const num = i + 1;
                        const val = serverLimits[String(num)] ?? currentMax;
                        const numVal = parseInt(val, 10) || 0;

                        // حساب محاكيات هذا السيرفر
                        const inServer = emulators?.filter(e => e.index_server === num && e.Is_OK === "true").length || 0;
                        const pct = numVal > 0 ? Math.round((inServer / numVal) * 100) : 0;
                        const barColor = pct >= 100 ? "var(--red)" : pct >= 80 ? "var(--gold)" : "var(--green)";

                        return (
                            <div key={num} style={{
                                padding: "1rem",
                                background: "var(--bg-surface)",
                                borderRadius: "var(--radius-sm)",
                                border: `1px solid ${pct >= 100 ? "rgba(239,68,68,0.4)" : "var(--border)"}`,
                                display: "flex", flexDirection: "column", gap: "0.625rem",
                            }}>
                                <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                                    <span style={{ fontWeight: 700, fontSize: "0.875rem" }}>
                                        🖥️ سيرفر {num}
                                    </span>
                                    <span style={{ fontSize: "0.72rem", color: "var(--text-muted)", fontWeight: 600 }}>
                                        {inServer}/{numVal}
                                    </span>
                                </div>

                                {/* شريط الامتلاء */}
                                <div style={{ height: 5, background: "var(--bg-hover)", borderRadius: 999, overflow: "hidden" }}>
                                    <div style={{ height: "100%", width: `${Math.min(pct, 100)}%`, background: barColor, borderRadius: 999, transition: "width 0.4s" }} />
                                </div>

                                {/* حقل الإدخال */}
                                <div style={{ display: "flex", alignItems: "center", gap: "0.375rem" }}>
                                    <button className="btn btn-ghost" style={{ padding: "0.25rem 0.5rem" }}
                                        onClick={() => handleLimitChange(num, String(Math.max(1, numVal - 1)))}>
                                        <Minus size={12} />
                                    </button>
                                    <input
                                        className="form-input"
                                        type="number"
                                        min={1}
                                        max={999}
                                        value={val}
                                        onChange={(e) => handleLimitChange(num, e.target.value)}
                                        style={{ flex: 1, textAlign: "center", padding: "0.35rem 0.5rem", fontWeight: 700, fontSize: "1rem" }}
                                    />
                                    <button className="btn btn-ghost" style={{ padding: "0.25rem 0.5rem" }}
                                        onClick={() => handleLimitChange(num, String(numVal + 1))}>
                                        <Plus size={12} />
                                    </button>
                                </div>
                            </div>
                        );
                    })}
                </div>

                <p style={{ marginTop: "0.75rem", fontSize: "0.78rem", color: "var(--text-muted)" }}>
                    <Info size={11} style={{ display: "inline", marginRight: 3 }} />
                    الطاقة الكلية: <strong style={{ color: "var(--accent)" }}>{totalSlots}</strong> مقعد ·
                    مشغول: <strong style={{ color: "var(--gold)" }}>{approvedCount}</strong> ·
                    متاح: <strong style={{ color: "var(--green)" }}>{Math.max(totalSlots - approvedCount, 0)}</strong>
                </p>
            </div>

            {/* ── حالة النظام ── */}
            <div className="card" style={{ padding: "1.5rem" }}>
                <h2 style={{ font: "700 1rem/1 inherit", marginBottom: "1rem", color: "var(--text-secondary)" }}>{t("systemStatus")}</h2>
                <div style={{ marginBottom: "1rem" }}>
                    <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "0.375rem" }}>
                        <span style={{ fontSize: "0.8rem", color: "var(--text-muted)" }}>{approvedCount} / {totalSlots}</span>
                        <span style={{ fontSize: "0.8rem", fontWeight: 700, color: usedPct >= 90 ? "var(--red)" : usedPct >= 70 ? "var(--gold)" : "var(--green)" }}>{usedPct}%</span>
                    </div>
                    <div style={{ height: 8, background: "var(--bg-hover)", borderRadius: 999, overflow: "hidden" }}>
                        <div style={{ height: "100%", width: `${Math.min(usedPct, 100)}%`, background: usedPct >= 90 ? "var(--red)" : usedPct >= 70 ? "var(--gold)" : "var(--green)", borderRadius: 999, transition: "width 0.5s" }} />
                    </div>
                </div>
                <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: "0.75rem" }}>
                    {[
                        { label: t("totalEmulators"), value: emulators?.length || 0, color: "var(--accent)" },
                        { label: t("activeApproved"), value: approvedCount, color: "var(--green)" },
                        { label: t("requiredServers"), value: `${usedServers} / ${currentServers}`, color: usedServers > currentServers ? "var(--red)" : "var(--green)" },
                        { label: t("freeSlots") || "متاح", value: Math.max(totalSlots - approvedCount, 0), color: "var(--green)" },
                    ].map(({ label, value, color }) => (
                        <div key={label} style={{ padding: "0.875rem", background: "var(--bg-surface)", borderRadius: "var(--radius-sm)", border: "1px solid var(--border)", borderTop: `3px solid ${color}` }}>
                            <div style={{ fontSize: "0.68rem", color: "var(--text-muted)", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "0.35rem" }}>{label}</div>
                            <div style={{ fontSize: "1.375rem", fontWeight: 800, color }}>{value}</div>
                        </div>
                    ))}
                </div>
            </div>

            {/* ── SQL Setup ── */}
            <div className="card" style={{ padding: "1.5rem" }}>
                <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "1rem", flexWrap: "wrap", gap: "0.5rem" }}>
                    <div style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
                        <AlertCircle size={18} color="var(--gold)" />
                        <h2 style={{ font: "700 1rem/1 inherit", color: "var(--gold)" }}>{t("dbSetup")} — Full SQL Setup</h2>
                    </div>
                    <button className="btn btn-secondary" onClick={handleCopy} style={{ gap: "0.4rem", fontSize: "0.8rem" }}>
                        {copied ? <><Check size={14} color="var(--green)" /> تم!</> : <><Copy size={14} /> نسخ SQL</>}
                    </button>
                </div>
                <p style={{ color: "var(--text-muted)", fontSize: "0.825rem", marginBottom: "1rem" }}>
                    يشمل: <strong>جميع الجداول · دالة reindex_v2 (حدود مخصصة لكل سيرفر) · RLS · القيم الافتراضية</strong>
                </p>
                <pre style={{
                    background: "var(--bg-base)", border: "1px solid var(--border)", borderRadius: "var(--radius-sm)",
                    padding: "1.25rem", overflowX: "auto", fontSize: "0.75rem", color: "var(--text-secondary)",
                    lineHeight: 1.7, direction: "ltr", textAlign: "left", maxHeight: 420, overflowY: "auto",
                }}>
                    {FULL_SETUP_SQL}
                </pre>
            </div>
        </div>
    );
}
